### ISSUE TITLE
Package is not available on unpkg.com

### ISSUE THREAD

**Issue by michaelx169** [darkwave/aframe-stl-model-component#2]
https://unpkg.com/aframe-stl-model-component/dist/aframe-stl-model-component.min.js
Cannot find package "aframe-stl-model-component"

**Comment by darkwave** [comment]
I didn't published it on [npmjs](https://npmjs.com) as a node module so It's not available on [unpkg](https://unpkg.com) :face_with_head_bandage: 

I suggest to use this link instead: [https://rawgit.com/darkwave/aframe-stl-model-component/master/dist/aframe-stl-model-component.min.js](https://rawgit.com/darkwave/aframe-stl-model-component/master/dist/aframe-stl-model-component.min.js)
